FROM phusion/passenger-ruby32:2.5.1
ENV PASSENGER_DISABLE_SECURITY_UPDATE_CHECK=true HOME=/app
WORKDIR /app

# Install dumb-init
RUN curl -s -L -o /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_$(uname -m) \
    && chmod +x /usr/local/bin/dumb-init

ENTRYPOINT ["/usr/local/bin/dumb-init"]
CMD ["passenger", "start", "--port", "80", "--log-file=/dev/stdout", "--nginx-config-template", "/nginx.conf.erb"]

# Install bundler and configure
RUN gem install bundler \
    && bundle config --global silence_root_warning 1

# Install monitor app dependencies
COPY src/Gemfile /monitor/Gemfile
RUN cd /monitor && bundle install

# Copy configuration and applications
COPY test/nginx-configurations/nginx.conf.erb /nginx.conf.erb
COPY src/ /monitor/

# Create dummy app structure
RUN mkdir -p /app/public && echo '<html><body><p>Nothing to see here!</p></body></html>' > /app/public/index.html

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD curl -f http://localhost/monitus/metrics || exit 1
