source 'https://rubygems.org'

# Version-aware dependency management
ruby_version = Gem::Version.new(RUBY_VERSION)

if ruby_version >= Gem::Version.new('3.0.0')
  # Modern Ruby (3.0+) - use current versions
  gem 'nokogiri', '>= 1.12.0'  # Modern nokogiri for Ruby 3.0+
  gem 'sinatra', '~> 2.2.0'     # Modern sinatra
  gem 'rack', '>= 2.2.0'        # Modern rack
  gem 'puma', '>= 5.0.0'        # Modern puma
  gem 'rackup'                  # Required for modern Ruby
  gem 'net-ftp'                 # Explicitly include net-ftp for Ruby 3.1+
elsif ruby_version >= Gem::Version.new('2.4.0')
  # Ruby 2.4-2.7 - balanced versions
  gem 'nokogiri', '~> 1.11.0'   # Compatible with Ruby 2.4-2.7
  gem 'sinatra', '~> 2.1.0'     # Compatible version
  gem 'rack', '~> 2.1.0'        # Compatible version
  gem 'puma', '~> 4.3.0'        # Compatible version
  gem 'rackup'                  # Available for Ruby 2.4+
else
  # Ruby 2.3.8 - legacy versions
  gem 'nokogiri', '~> 1.10.10'  # Last version supporting Ruby 2.3.8
  gem 'sinatra', '~> 2.0.8'     # Compatible with Ruby 2.3.8
  gem 'rack', '~> 2.0.9'        # Core dependency for Ruby 2.3.8
  gem 'puma', '~> 3.12.6'       # Compatible with Ruby 2.3.8
  # No rackup gem for Ruby 2.3.8 - built into rack
end
